version: '3.7'
services:
  backend:
    build: backend
    volumes:
      - media:/app/media
      - static:/app/static
    environment:
      - DJANGO_SECRET_KEY=<YOUR_DJANGO_SECRET_KEY>
      - CSRF_TRUSTED_ORIGINS=http://*.localhost
      - CORS_ORIGIN_WHITELIST=http://localhost
  client:
    build: client
    depends_on:
      - backend
  nginx:
    build: nginx
    volumes:
      - media:/media
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=localhost
      - DJANGO_PORT=8000
      - FRONTEND_PORT=80

volumes:
  media:
  static:
