version: '3.7'
services:
  backend:
    image: pycrs/remeslovkostce-backend:latest
    volumes:
      - /home/administrator/docker/remeslovkostce/data/media:/app/media
      - /home/administrator/docker/remeslovkostce/data/db.sqlite3:/app/db.sqlite3
      - static:/app/static
    environment:
      - DJANGO_SECRET_KEY=<YOUR_DJANGO_SECRET_KEY>
      - CSRF_TRUSTED_ORIGINS=https://remeslovkostce.cz
      - CORS_ORIGIN_WHITELIST=https://remeslovkostce.cz
  client:
    image: pycrs/remeslovkostce-client
    depends_on:
      - backend
  nginx:
    image: pycrs/remeslovkostce-proxy
    volumes:
      - /home/administrator/docker/remeslovkostce/data/media:/app/media
      - static:/static
    environment:
      - DOMAIN=localhost
      - DJANGO_PORT=8000
      - FRONTEND_PORT=80
    ports:
      - "8100:80"

volumes:
  static:
