# Generated by Django 4.2.3 on 2023-07-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='hex',
            field=models.CharField(blank=True, default='FFFFFF', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remeslovkostce.productsizelabel'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='sheet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
