# Generated by Django 4.2.3 on 2023-07-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0002_alter_productcolor_hex_alter_productsize_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remeslovkostce.productsize'),
        ),
    ]
