# Generated by Django 4.2.3 on 2023-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0004_alter_productsize_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_dimensions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_sheet_count',
            field=models.BooleanField(default=True),
        ),
    ]
