# Generated by Django 4.2.3 on 2023-07-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0008_product_prefer_label_alter_product_show_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prefer_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_sheet_count',
        ),
        migrations.CreateModel(
            name='SizeDisplayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_label', models.BooleanField(default=True, help_text='Zahrnovat popisek velikosti do názvu produktu')),
                ('show_sheet_count', models.BooleanField(default=True, help_text='Zahrnovat počet listů do názvu produktu')),
                ('show_dimensions', models.BooleanField(default=False, help_text='Zahrnovat rozměry do názvu produktu')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remeslovkostce.productsize')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size_display_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remeslovkostce.sizedisplayconfiguration'),
        ),
    ]
