# Generated by Django 4.2.3 on 2023-07-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0009_remove_product_prefer_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizedisplayconfiguration',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remeslovkostce.productsize'),
        ),
    ]
