# Generated by Django 4.2.3 on 2023-07-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0011_alter_product_size_display_configuration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_thumbnail',
            new_name='thumbnail',
        ),
    ]
