# Generated by Django 4.2.3 on 2023-07-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0014_alter_product_description_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remeslovkostce.variantgroup'),
        ),
    ]
