# Generated by Django 4.2.3 on 2023-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0015_variantgroup_product_variant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='remeslovkostce.tag'),
        ),
    ]
