# Generated by Django 4.2.3 on 2023-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0016_productcategory_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('category', 'Tagy kategorií'), ('product', 'Tagy produktů'), ('product_color', 'Tagy barev produktů'), ('product_size', 'Tagy velikostí produktů'), ('variant_group', 'Tagy skupin variant')], default='product', max_length=16),
            preserve_default=False,
        ),
    ]
