# Generated by Django 4.2.3 on 2023-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0018_productcolor_tags_productsize_tags_variantgroup_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('category', 'Tag kategorie'), ('product', 'Tag produktu'), ('product_color', 'Tag barvy produktu'), ('product_size', 'Tag velikosti produktu'), ('variant_group', 'Tag skupiny variant')], max_length=16),
        ),
    ]
