# Generated by Django 4.2.3 on 2023-07-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remeslovkostce', '0020_productcategory_order_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('order_weight',), 'verbose_name_plural': 'Product categories'},
        ),
    ]
