name: Test and build Pull Requests
on:
  workflow_dispatch: # Allows to run the workflow manually from the Actions tab
  pull_request:
    branches: [ main, develop ]
jobs:
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting
        run: pylint --load-plugins=pylint_django --django-settings-module=backend.settings api backend remeslovkostce
      - name: Run tests and Coverage report
        run: |
          coverage run manage.py test
          coverage report
